### PR TITLE
Add 'craft_guide' as optional dependency

### PR DESCRIPTION
**Pull request by AntumDeluge**

### CODE REVIEW

**Comment by cornernote** [comment]
Does craft_guide have any code relating to this mod?

**Comment by AntumDeluge** [comment]
This just ensures that *craft_guide* is loaded first so that the bags' craft recipes are registered in it.

But if newer releases of *craft_guide* register craft recipes in a different manner, then this would be obsolete. I'm not aware of any change like that though.

**Comment by cornernote** [comment]
Doing this would mean adding every other mod to the repo. I'd prefer to
find a better way. What are your thoughts?

**Comment by AntumDeluge** [comment]
Sorry, I'm not sure what you mean by "Doing this would mean adding every other mod to the repo". But there is a [suggestion here on changing the way *craft_guide* works](https://github.com/cornernote/minetest-craft_guide/issues/20).

**Pull request closed without merging**
